=== Mikk155/Sven-Co-op/schemas/assets.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties":
    {
        "$schema":
        {
            "type": "string"
        },
        "assets":
        {
            "type": "array",
            "description": "List of assets"
        },
        "includes":
        {
            "type": "array",
            "description": "Include extra assets json"
        },
        "map_script":
        {
            "type": "boolean",
            "description": "Is this a script for maps?"
        },
        "plugin":
        {
            "type": "boolean",
            "description": "Is this a plugin for servers?"
        },
        "name":
        {
            "type": "string",
            "description": "Name of the asset as-is"
        },
        "title":
        {
            "type": "string",
            "description": "Name"
        },
        "description":
        {
            "type": "string",
            "description": "Description for the header"
        },
        "metamod":
        {
            "type": "string",
            "enum": [
                "required",
                "optional",
                "no"
            ],
            "description": "Does this require metamod to some extent?"
        },
        "short_description":
        {
            "type": "string",
            "description": "Short description for the main table"
        },
        "details":
        {
            "type": "string",
            "description": "Path to a .html file in docs/ to add in the generated html"
        }
    },
    "additionalProperties": false,
    "required":
    [
        "name",
        "assets"
    ]
}

=== Mikk155/Sven-Co-op/src/publisher/definitions/ShowPlayTime.json
{
    "$schema": "../../../schemas/assets.json",

    "assets":
    [
        "scripts/plugins/ShowPlayTime.as",
        "scripts/plugins/ShowPlayTime.json",
        "scripts/mikk155/meta_api.as",
        "scripts/mikk155/meta_api/json/v1.as",
        "scripts/mikk155/meta_api/json.as"
    ],

    "short_description": "Display the total time a map has been running on the server",

    "map_script": false,

    "plugin": true,

    "metamod": "optional",

    "name": "ShowPlayTime",

    "details": "angelscript/ShowPlayTime.html",

    "title": "Show map play time"
}

=== Mikk155/Sven-Co-op/src/publisher/definitions/ChatRoles.json
{
    "$schema": "../../../schemas/assets.json",

    "assets":
    [
        "scripts/plugins/ChatRoles.as",
        "scripts/plugins/ChatRoles.json"
    ],

    "description": "Set custom roles and colors to player names in chat",

    "map_script": false,

    "plugin": true,

    "metamod": "optional",

    "name": "ChatRoles",

    "title": "Chat Roles"
}

=== Mikk155/Sven-Co-op/src/publisher/definitions/ShowFrameRate.json
{
    "$schema": "../../../schemas/assets.json",

    "assets":
    [
        "scripts/plugins/ShowFrameRate.as"
    ],

    "short_description": "Allow players to see the server frame-rate information by a .framerate command",

    "map_script": false,

    "plugin": true,

    "metamod": "no",

    "name": "ShowFrameRate",

    "details": "angelscript/ShowFrameRate.html",

    "title": "Show server frame rate"
}

=== Mikk155/Sven-Co-op/src/publisher/definitions/FastRestart.json
{
    "$schema": "../../../schemas/assets.json",

    "assets":
    [
        "scripts/plugins/FastRestart.as",
        "scripts/plugins/FastRestart.json"
    ],

    "description": "Restart the map inmediatelly when a survival mode round is about to end.",

    "map_script": false,

    "plugin": true,

    "metamod": "optional",

    "name": "FastRestart",

    "title": "Survival Mode fast restart"
}

=== Mikk155/Sven-Co-op/src/publisher/definitions/anticlip.json
{
    "$schema": "../../../schemas/assets.json",

    "assets":
    [
        "scripts/plugins/anticlip.as",
        "scripts/plugins/anticlip.json",
        "scripts/mikk155/meta_api.as",
        "scripts/mikk155/meta_api/json/v1.as",
        "scripts/mikk155/meta_api/json.as",
        "scripts/mikk155/Server/Framerate.as",
        "scripts/mikk155/Server/IsMapListed.as"
    ],

    "short_description": "Disable allied characters collision. Pass through players and allied monsters like in Left 4 dead",

    "map_script": false,

    "plugin": true,

    "metamod": "required",

    "name": "anticlip",

    "details": "angelscript/anticlip.html",

    "title": "Anti Clip"
}

=== Mikk155/Sven-Co-op/src/publisher/definitions/UnforcePlayermodels.json
{
    "$schema": "../../../schemas/assets.json",

    "assets":
    [
        "scripts/plugins/UnforcePlayermodels.as"
    ],

    "description": "Allow players to use any model at any map that enforces a selected list.",

    "map_script": false,

    "plugin": true,

    "metamod": "no",

    "name": "UnforcePlayermodels",

    "title": "Un-force player models"
}

=== Mikk155/Sven-Co-op/src/publisher/definitions/BMLongJump.json
{
    "$schema": "../../../schemas/assets.json",

    "assets":
    [
        "scripts/plugins/BMLongJump.as",
        "scripts/plugins/BMLongJump.json"
    ],

    "short_description": "Double tap space to long jump. to any direction.",

    "map_script": false,

    "plugin": true,

    "metamod": "optional",

    "name": "BMLongJump",

    "title": "Black-Mesa Long jump module"
}

=== Mikk155/Sven-Co-op/src/publisher/definitions/CustomPrecache.json
{
    "$schema": "../../../schemas/assets.json",

    "assets":
    [
        "scripts/plugins/CustomPrecache.as",
        "scripts/plugins/CustomPrecache.json"
    ],

    "short_description": "Set a list of any type of asset to statically or dynamically precache across levels.",

    "details": "angelscript/CustomPrecache.html",

    "map_script": false,

    "plugin": true,

    "metamod": "optional",

    "name": "CustomPrecache",

    "title": "Custom Precache"
}
