=== Mikk155/Sven-Co-op/schemas/assets.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties":
    {
        "$schema":
        {
            "type": "string"
        },
        "assets":
        {
            "type": "array",
            "description": "List of assets"
        },
        "includes":
        {
            "type": "array",
            "description": "Include extra assets json"
        },
        "map_script":
        {
            "type": "boolean",
            "description": "Is this a script for maps?"
        },
        "plugin":
        {
            "type": "boolean",
            "description": "Is this a plugin for servers?"
        },
        "name":
        {
            "type": "string",
            "description": "Name of the asset as-is"
        },
        "title":
        {
            "type": "string",
            "description": "Name"
        },
        "description":
        {
            "type": "string",
            "description": "Description for the header"
        },
        "metamod":
        {
            "type": "string",
            "enum": [
                "required",
                "optional",
                "no"
            ],
            "description": "Does this require metamod to some extent?"
        },
        "short_description":
        {
            "type": "string",
            "description": "Short description for the main table"
        },
        "details":
        {
            "type": "string",
            "description": "Path to a .html file in docs/ to add in the generated html"
        }
    },
    "additionalProperties": false,
    "required":
    [
        "name",
        "assets"
    ]
}

=== Mikk155/Sven-Co-op/src/publisher/definitions/env_decal.json
{
    "$schema": "../../../schemas/assets.json",

    "assets":
    [
        "scripts/maps/mikk155/CustomEntity/env_decal.as",
        "scripts/maps/mikk155/CustomEntity/env_decal.fgd"
    ],

    "description": "Players joining the server after a infodecal was triggered won't see such decal.\nThis custom entity fixes that by keeping track of the decals it paint and sending them to late join players.",

    "map_script": true,

    "plugin": false,

    "metamod": "no",

    "name": "env_decal",

    "title": "Environment Decal"
}

=== Mikk155/Sven-Co-op/src/publisher/definitions/SurvivalLateJoinSpawn.json
{
    "$schema": "../../../schemas/assets.json",

    "assets":
    [
        "scripts/plugins/SurvivalLateJoinSpawn.as",
        "scripts/plugins/SurvivalLateJoinSpawn.json"
    ],

    "short_description": "Allow late join players to spawn for a first time if survival mode is been activated.",

    "map_script": false,

    "plugin": true,

    "metamod": "optional",

    "name": "SurvivalLateJoinSpawn",

    "details": "angelscript/SurvivalLateJoinSpawn.html",

    "title": "Survival Mode late join players respawn"
}
